### ISSUE TITLE
[Feature Request] Ability to choose a list of predefined inputs and define an action to that input

### ISSUE THREAD

**Issue by Terkyz** [eatsu/plasmoid-spacer-as-pager#2]
With a list of predefined inputs I mean that when configuring the widget options, a box appears with the typical mouse inputs "right click, middle click, left click" and that the user has the ability (or a list) to choose which function he wants to choose according to each input, such as open the overview, close the current window, open the grid view, etc.

**Comment by eatsu** [comment]
Added middle-click and right-click sections and the "show grid view" predefined click action.

> close the current window

Sorry, but didn't add it as a predefined click action because it sounds a bit too niche to me. But you can manually set it by selecting "Run Command" and pasting `qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Window Close'` into the text field. :wink:
