### ISSUE TITLE
Click actions not working on Fedora KDE 40 Wayland

### ISSUE THREAD

**Issue by gianmarcogg03** [eatsu/plasmoid-spacer-as-pager#5]
Only scrolling between desktops works. Maybe a dependency is missing?

**Comment by eatsu** [comment]
Thank you for reporting the bug.

This seems to be because in Fedora the qt6 version of qdbus is located at `/usr/bin/qdbus-qt6` instead of `/usr/lib/qt6/bin/qdbus`.

I'll think of a workaround.

As a workaround for now you might want to manually edit `~/.local/share/plasma/plasmoids/com.github.eatsu.spaceraspager/contents/ui/main.qml` and replace all `/usr/lib/qt6/bin/qdbus` with `/usr/bin/qdbus-qt6`.

**Comment by gianmarcogg03** [comment]
The workaround worked, thanks, I guess I'll leave this open until you find a proper solution.
